[project]
name = "nauchka"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "astropy>=8.0.1",
    "astroquery>=0.4.11",
    "dearpygui>=2.3.1",
    "ipyaladin>=0.8.0",
    "ipykernel>=7.3.0",
    "ipympl>=0.10.0",
    "lightkurve>=2.6.0",
    "matplotlib>=3.11.1",
    "numpy>=2.4.6",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "photutils>=3.0.0",
    "scipy>=1.17.1",
]
